### ISSUE TITLE
Import Error when running from nox in woodpecker...

### ISSUE THREAD

**Issue by marvin8** [getcodelimit/codelimit#57]
I am getting an error when I run 0.14.1 using NOX under Woodpecker CI. Relevant output from CI run as below:

```
nox > Running session refactor
nox > Creating virtual environment (uv) using python in .nox/refactor
nox > uv pip install codelimit
nox > codelimit check src
Traceback (most recent call last):
  File "/woodpecker/src/codeberg.org/marvinsmastodontools/minimal-activitypub/.nox/refactor/bin/codelimit", line 5, in <module>
    from codelimit.__main__ import cli
  File "/woodpecker/src/codeberg.org/marvinsmastodontools/minimal-activitypub/.nox/refactor/lib/python3.13/site-packages/codelimit/__main__.py", line 10, in <module>
    from codelimit.commands.check import check_command
  File "/woodpecker/src/codeberg.org/marvinsmastodontools/minimal-activitypub/.nox/refactor/lib/python3.13/site-packages/codelimit/commands/check.py", line 9, in <module>
    from codelimit.common.CheckResult import CheckResult
  File "/woodpecker/src/codeberg.org/marvinsmastodontools/minimal-activitypub/.nox/refactor/lib/python3.13/site-packages/codelimit/common/CheckResult.py", line 9, in <module>
    from codelimit.common.utils import format_measurement
  File "/woodpecker/src/codeberg.org/marvinsmastodontools/minimal-activitypub/.nox/refactor/lib/python3.13/site-packages/codelimit/common/utils.py", line 10, in <module>
    from sh import git, ErrorReturnCode
ImportError: cannot import name 'git' from 'sh' (unknown location)
nox > Command codelimit check src failed with exit code 1
```

Code in noxfile.py is very simple:
```python
@nox.session
def refactor(session):
    session.install("codelimit")
    session.run("codelimit", "check", "src")
```

When I force a downgrade to less than 0.14.0 in my setup codelimit works as expected.

**Comment by marvin8** [comment]
Sorry, just remembered to also provide you with a link to the full CI output:

https://ci.codeberg.org/repos/12828/pipeline/174/3

**Comment by robvanderleek** [comment]
Hi @marvin8 

Thanks a lot for reporting this issue 😄 

I've pushed a fix in 0.14.2, let me know if this still does not work of course.

KR, Rob

**Comment by marvin8** [comment]
Thanks @robvanderleek 

That fixed it for me! Yay!

Have a happy holiday period; I very much appreciate your work.

**Comment by robvanderleek** [comment]
Thanks for your kind words, have a wonderful holiday period too!

Also, do not hesitate to open new issues for feature requests, bug reports, etc. Your feedback is appreciated 😄
